config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  post 'sessions/create'

  get 'sessions/delete'
  
  delete 'sessions/log_out'
  resources :logins
  resources :accounts

  namespace :apis do
    resources :accounts
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord

    validates :f_name, :age, presence: true
    validates :email, uniqueness: true, presence: true, confirmation: true
    validates :email_confirmation, presence: true
    validates :password, length: { in: 8..12 }
    # validates :gender, acceptance: { message: 'must be abided' }    

    before_validation :age_method

    after_validation :Sucessfully_validate

    before_validation :create_name, on: :create

    
    before_create :default_date

    after_create :just_created

    after_save :save_sucessfully

    before_destroy :delete_method


    after_destroy :delete_the_record

    mount_uploader :cover, CoverUploader


private


    before_create do |account|
        puts "about to create #{account.f_name}"
    end


    def age_method
        if age.blank?
            self.age = 25
        end
    end


    def Sucessfully_validate
        self.l_name = l_name.downcase
    end

    def create_name
        if f_name.blank?
            self.f_name = "default"
        end
    end


    def default_date
        self.date = Date.yesterday
     end

     def just_created
        puts "just created a account"
    end


    

    def save_sucessfully
        puts "data is saved sucessfully"
    end


    def delete_method
        if l_name.blank?
            puts "last name is not there"
        end
    end



    def delete_the_record
        if self.present?
            puts "... happy path"
          else
            puts "... sad path"
          end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/login.rb
class Login < ApplicationRecord
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # before_action :check_user_present
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:f_name, :l_name, :email, :email_confirmation, :password, :age, :date, :gender, :cover)
    end
end

app/controllers/apis/accounts_controller.rb
module Apis
    class AccountsController < ApplicationController

        def index
            puts "...."
            @accounts = Account.all
            render :json => @accounts
        end
        
        def create
            putss "........."
            @accoount= Account.new

            # @accoount
            puts params.inpsect
            render "s....."
            render :json => @account
        end

    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def check_user_present
    puts session[:currrent_user]
    if session[:currrent_user].present?
      true
    else
      redirect_to sessions_new_path
    end
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:show, :edit, :update, :destroy]

  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        puts "step1......."
        UserMailer.registration_confirmation(@login).deliver

        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { render :show, status: :ok, location: @login }
      else
        format.html { render :edit }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:f_name, :l_name, :email, :password, :date, :gender, :phn_no)
    end
end


      

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
   
  end

  def create
    @user = Login.find_by(email: params[:login][:email])
    puts params[:login][:password]
    puts @user.try(:password)
    if @user.try(:password) == params[:login][:password]
      session[:currrent_user] = @user.email
      redirect_to accounts_path
    else
      session[:currrent_user] = nil
      redirect_to sessions_new_path
    end
  end

  def log_out
    puts "log_out"
   session[:currrent_user] = nil
    redirect_to sessions_new_path
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true, validate: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :f_name %>
    <%= form.text_field :f_name, id: :account_f_name %>
  </div>

  <div class="field">
    <%= form.label :l_name %>
    <%= form.text_field :l_name, id: :account_l_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, id: :account_email%>
  </div>

  <div class="field">
    <%= form.label :email_confirmation %>
    <%= form.email_field :email_confirmation, id: :account_confirm_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :account_password %>
  </div>

  
  <div class="field">
    <%= form.label :date, "DOB"%>
    <%=form.text_field :date, onchange: "age_calculate(this)"%>
    <%# <%= form.date_select :date, id: :account_date%>
  </div>

  <div id="age_div" style="display: none;">
    <%= form.label :age %>
    <%= form.number_field :age, id: :account_age %>
  </div>

  <div class="field">
        <%= form.label :Gender %> <br />
        <%= form.label :Gender, 'male' %>
        <%= form.radio_button :gender, 0 %>
        <%= form.label :Gender, 'female' %>
        <%= form.radio_button :gender, 1 %><br />
      </div>

  <div class="field">
    <%= form.label :cover %> 
    <%= form.file_field :cover %>
  </div>


  <div class="actions">
    <%= form.submit 'SignUp'%>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>F name</th>
      <th>L name</th>
      <th>Email</th>
      <th>Confirm email</th>
      <th>Password</th>
      <th>Age</th>
      <th>Date</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.f_name %></td>
        <td><%= account.l_name %></td>
        <td><%= account.email %></td>
        <td><%= account.confirm_email %></td>
        <td><%= account.password %></td>
        <td><%= account.age %></td>
        <td><%= account.date %></td>
        <td><%= account.gender %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>F name:</strong>
  <%= @account.f_name %>
</p>

<p>
  <strong>L name:</strong>
  <%= @account.l_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @account.email %>
</p>

<p>
  <strong>Confirm email:</strong>
  <%= @account.confirm_email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @account.password %>
</p>

<p>
  <strong>Age:</strong>
  <%= @account.age %>
</p>

<p>
  <strong>Date:</strong>
  <%= @account.date %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @account.gender %>
</p>


  <%= image_tag @account.cover.url if @account.cover? %> 



<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Validation</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="https://apis.google.com/js/api.js"></script>
  </head>
  
  <body>
  <%if session[:currrent_user]%>
  <%= link_to 'log_out', sessions_log_out_path, method: :delete%>
  <%end%>
    <%= yield %>
  </body>
</html>

app/views/logins/_form.html.erb
<%= form_with(model: login, local: true) do |form| %>
  <% if login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% login.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :f_name %>
    <%= form.text_field :f_name, id: :login_f_name %>
  </div>

  <div class="field">
    <%= form.label :l_name %>
    <%= form.text_field :l_name, id: :login_l_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, id: :login_email %>
  </div>

  <div class="field">
    <%= form.label :email_confirmation %>
    <%= form.email_field :email_confirmation, id: :account_confirm_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :login_password %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :login_date %>
  </div>

  <div class="field">
        <%= form.label :Gender %> <br />
        <%= form.label :Gender, 'male' %>
        <%= form.radio_button :gender, 0 %>
        <%= form.label :Gender, 'female' %>
        <%= form.radio_button :gender, 1 %><br />
  </div>

  <div class="field">
    <%= form.label :phn_no %>
    <%= form.number_field :phn_no, id: :login_phn_no %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing Login</h1>

<%= render 'form', login: @login %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Logins</h1>

<table>
  <thead>
    <tr>
      <th>F name</th>
      <th>L name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Date</th>
      <th>Gender</th>
      <th>Phn no</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logins.each do |login| %>
      <tr>
        <td><%= login.f_name %></td>
        <td><%= login.l_name %></td>
        <td><%= login.email %></td>
        <td><%= login.password %></td>
        <td><%= login.date %></td>
        <td><%= login.gender %></td>
        <td><%= login.phn_no %></td>
        <td><%= link_to 'Show', login %></td>
        <td><%= link_to 'Edit', edit_login_path(login) %></td>
        <td><%= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Login', new_login_path %>

app/views/logins/new.html.erb
<h1>New Login</h1>

<%= render 'form', login: @login %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>F name:</strong>
  <%= @login.f_name %>
</p>

<p>
  <strong>L name:</strong>
  <%= @login.l_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @login.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @login.password %>
</p>

<p>
  <strong>Date:</strong>
  <%= @login.date %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @login.gender %>
</p>

<p>
  <strong>Phn no:</strong>
  <%= @login.phn_no %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>

app/views/logins/sign_in.html.erb
<h1>SignIn</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:login,  url: user_logins_path() ) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now", new_login_path %></p>
  </div>
</div>